"""Built-in wordlist of common hidden / interesting parameters (~150)."""

DEFAULT_PARAMS = [
    'name', 'debug', 'id', 'user', 'admin', 'q',
    'token', 'file', 'url', 'redirect', 'username', 'userid',
    'user_id', 'uid', 'account', 'account_id', 'email', 'fullname',
    'profile', 'member', 'customer', 'customer_id', 'client', 'client_id',
    'org', 'org_id', 'tenant', 'role', 'roles', 'group',
    'permission', 'is_admin', 'isadmin', 'access', 'level', 'type',
    'kind', 'test', 'dev', 'devel', 'development', 'staging',
    'env', 'environment', 'trace', 'verbose', 'log', 'bench',
    'page', 'p', 'offset', 'limit', 'size', 'count',
    'per_page', 'start', 'end', 'from', 'to', 'sort',
    'order', 'orderby', 'order_by', 'filter', 'view', 'mode',
    'display', 'format', 'fmt', 'output', 'lang', 'locale',
    'language', 'filename', 'filepath', 'path', 'dir', 'directory',
    'folder', 'document', 'doc', 'template', 'tpl', 'include',
    'require', 'load', 'src', 'source', 'dest', 'destination',
    'target', 'resource', 'uri', 'link', 'href', 'redirect_uri',
    'redirect_url', 'return', 'return_to', 'returnUrl', 'return_url', 'next',
    'next_url', 'continue', 'goto', 'callback', 'cb', 'jsonp',
    'success_url', 'failure_url', 'query', 'search', 's', 'keyword',
    'keywords', 'term', 'text', 'message', 'msg', 'content',
    'body', 'data', 'payload', 'input', 'value', 'key',
    'field', 'fields', 'access_token', 'auth', 'authorization', 'api_key',
    'apikey', 'api-key', 'secret', 'password', 'pass', 'passwd',
    'pwd', 'session', 'session_id', 'sid', 'csrf', 'csrf_token',
    'state', 'nonce', 'code', 'action', 'act', 'do',
]
